name: enhanzer_login
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_launcher_icons: ^0.14.3
  dynamic_background: ^0.1.3
  modern_textfield: ^0.0.6
  flutter_animated_button: ^2.0.4
  flutter_easyloading: ^3.0.5
  quickalert: ^1.1.0
  http: ^1.3.0
  sqflite: ^2.2.0+3
  path: ^1.9.0
  shared_preferences: ^2.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/icon/

